### ISSUE TITLE
Bug: acme issue job doesn't run if a certificate already exists

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-template-app#41]
The current behaviour is to check for the existence of `fullchain.cer` and do nothing if it exists.
Investigate why we implemented this behaviour in the first place.

The side-effect is that if the acme configuration changes (like the `webroot` for example), it stays cached in the <host>.conf file used by the renew script, and the acme renewal will be broken until a dev goes onto the PVC and removes the `fullchain.cer` file.

Suggested change: the acme issue job re-issues no matter what (since it's a manual trigger from Airflow), this would allow a non-dev to force re-issue the configuration if issues come up.

**Comment by matthieu-foucault** [comment]
Why is this pinned as high priority? Is it affecting applications currently running in prod?

**Comment by matthieu-foucault** [comment]
If the only is that the mount point change needs to be propagated to `acme.sh` stateful `.conf` file, then we could do this manually, instead of issuing new certificates.

**Comment by pbastia** [comment]
#### Affected deployments
ciip -test and -prod are currently affected and fail to renew their certificates (since we deployed the nginx container and changed the where webroot directory is mounted).

#### Logs

Airflow logs look like this:
```*** Reading remote log from gs://0fad32-test-airflow-logs/cas_ciip_portal_acme_renewal/cert_renewal/2021-12-05T08:00:00+00:00/2.log.
*** Previous log discarded: 404 GET https://storage.googleapis.com/download/storage/v1/b/0fad32-test-airflow-logs/o/cas_ciip_portal_acme_renewal%2Fcert_renewal%2F2021-12-05T08%3A00%3A00%2B00%3A00%2F2.log?alt=media: No such object: 0fad32-test-airflow-logs/cas_ciip_portal_acme_renewal/cert_renewal/2021-12-05T08:00:00+00:00/2.log: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)

[2021-12-06 08:07:15,944] {trigger_k8s_cronjob.py:101} CRITICAL - Current Status: Pending
[2021-12-06 08:07:15,944] {trigger_k8s_cronjob.py:104} CRITICAL - sleeping
[2021-12-06 08:07:20,956] {trigger_k8s_cronjob.py:101} CRITICAL - Current Status: Running
[2021-12-06 08:07:20,956] {trigger_k8s_cronjob.py:104} CRITICAL - sleeping
[2021-12-06 08:07:25,966] {trigger_k8s_cronjob.py:101} CRITICAL - Current Status: Failed
[2021-12-06 08:07:25,982] {trigger_k8s_cronjob.py:114} CRITICAL - 2021-12-06T08:07:19.019748196Z + /tmp/.acme.sh/acme.sh --cron --home /tmp/.acme.sh --server https://acme-v02.api.letsencrypt.org/directory --days 60
2021-12-06T08:07:19.084720616Z [Mon Dec  6 08:07:19 UTC 2021] ===Starting cron===2021-12-06T08:07:19.084817036Z 
2021-12-06T08:07:19.112628584Z [Mon Dec  6 08:07:19 UTC 2021] 2021-12-06T08:07:19.112726817Z Renew: 'test.ciip.gov.bc.ca'
2021-12-06T08:07:19.840122230Z [Mon Dec  6 08:07:19 UTC 2021] 2021-12-06T08:07:19.840215903Z Single domain='test.ciip.gov.bc.ca'
2021-12-06T08:07:19.919723525Z [Mon Dec  6 08:07:19 UTC 2021] Getting domain auth token for each domain2021-12-06T08:07:19.919787570Z 
2021-12-06T08:07:21.187428773Z [Mon Dec  6 08:07:21 UTC 2021] 2021-12-06T08:07:21.187535134Z Getting webroot for domain='test.ciip.gov.bc.ca'
2021-12-06T08:07:21.323266186Z [Mon Dec  6 08:07:21 UTC 2021] Verifying: test.ciip.gov.bc.ca2021-12-06T08:07:21.323357289Z 
2021-12-06T08:07:21.331358807Z mkdir: cannot create directory '/root': Permission denied
2021-12-06T08:07:21.331650044Z /tmp/.acme.sh/acme.sh: line 4395: /root/.well-known/acme-challenge/<redacted>: Permission denied
2021-12-06T08:07:21.333832676Z [Mon Dec  6 08:07:21 UTC 2021] 2021-12-06T08:07:21.333959898Z test.ciip.gov.bc.ca:Can not write token to file : /root/.well-known/acme-challenge/<redacted>2021-12-06T08:07:21.334007782Z 
2021-12-06T08:07:21.335349743Z rm: cannot remove '/root/.well-known': Permission denied2021-12-06T08:07:21.335384674Z 
2021-12-06T08:07:21.349098461Z [Mon Dec  6 08:07:21 UTC 2021] 2021-12-06T08:07:21.349212921Z Please add '--debug' or '--log' to check more details.2021-12-06T08:07:21.349271733Z 
2021-12-06T08:07:21.351267829Z [Mon Dec  6 08:07:21 UTC 2021] 2021-12-06T08:07:21.351386822Z See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh2021-12-06T08:07:21.351424345Z 
2021-12-06T08:07:21.766432834Z [Mon Dec  6 08:07:21 UTC 2021] 2021-12-06T08:07:21.766562136Z Error renew test.ciip.gov.bc.ca.2021-12-06T08:07:21.766605064Z 
2021-12-06T08:07:21.769993187Z [Mon Dec  6 08:07:21 UTC 2021] 2021-12-06T08:07:21.770037861Z ===End cron===

[2021-12-06 08:07:25,982] {trigger_k8s_cronjob.py:118} CRITICAL - Failed
[2021-12-06 08:07:25,982] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/trigger_k8s_cronjob.py", line 122, in trigger_k8s_cronjob
    raise Exception('Job Failed')
```

**Comment by pbastia** [comment]
Closing this bug, it's not actually one.
